### ISSUE TITLE
CSS: Constant height when filtering study groups

### ISSUE THREAD

**Issue by stain88** [codebuddiesdotorg/codebuddies#706] opened 2017-11-09 07:50 UTC
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
When you start filtering the Study Groups, each card no longer has a fixed height, leading to weird shuffles.

<img width="1236" alt="screen shot 2017-11-09 at 07 46 11" src="https://user-images.githubusercontent.com/8461452/32594085-741dca64-c522-11e7-91f5-1ef5db108594.png">

What is the expected behavior?
Same constant height as the unfiltered view, so all the cards line up nicely.

Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)
MacOS - Chrome, FF, Safari, so taking a stab at all

**Comment by railsstudent** [comment] 2017-11-11 14:48
@lpatmo  I find the root cause of the issue. Can you let me tackle it? Thanks.

**Comment by lpatmo** [comment] 2017-11-11 23:24
@railsstudent You are so on top of things, Connie! Thank you.

**Comment by lpatmo** [comment] 2017-11-11 23:26
Fixed by @railsstudent in https://github.com/codebuddiesdotorg/codebuddies/pull/710!

**Closed by lpatmo** 2017-11-11 23:26 UTC
Labels: Backlog, claimed, good-for-beginners, html-css
